"""Add followers column to profile Table

Revision ID: 1f77bcec4df9
Revises: 86e63bd46907
Create Date: 2024-09-06 21:31:44.383728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f77bcec4df9'
down_revision: Union[str, None] = '86e63bd46907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('followers_id', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'followers_id')
    # ### end Alembic commands ###
