"""create matches table

Revision ID: 4da40f612e0d
Revises: 04d419d9d281
Create Date: 2024-12-20 15:52:29.208321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4da40f612e0d'
down_revision: Union[str, None] = '04d419d9d281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('first_id', sa.Integer(), nullable=False),
    sa.Column('second_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['first_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['second_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    # ### end Alembic commands ###
