"""Correct errors

Revision ID: 5176398133b6
Revises: 5efd2163a28d
Create Date: 2024-09-13 17:44:13.260550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5176398133b6'
down_revision: Union[str, None] = '5efd2163a28d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('liked_profile_id', sa.Integer(), nullable=False))
    op.drop_constraint('likes_liked_profilke_id_fkey', 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'profiles', ['liked_profile_id'], ['id'])
    op.drop_column('likes', 'liked_profilke_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('liked_profilke_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key('likes_liked_profilke_id_fkey', 'likes', 'profiles', ['liked_profilke_id'], ['id'])
    op.drop_column('likes', 'liked_profile_id')
    # ### end Alembic commands ###
