"""create settings table

Revision ID: 76caba0324e7
Revises: 9068df6b235f
Create Date: 2025-01-05 21:07:51.250000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76caba0324e7'
down_revision: Union[str, None] = '9068df6b235f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings_tables',
    sa.Column('color_theme', sa.Enum('DARK', 'LIGHT', name='themes'), nullable=False),
    sa.Column('dynamic_navbar', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings_tables')
    # ### end Alembic commands ###
