"""Update Profiles Table

Revision ID: 7cc6ec9fba87
Revises: a4c83595dfef
Create Date: 2024-09-03 19:05:55.196637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cc6ec9fba87'
down_revision: Union[str, None] = 'a4c83595dfef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'gender',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', 'BOY', 'GIRL', name='genders'),
               nullable=True)
    op.alter_column('profiles', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('profiles', 'hobbies',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'hobbies',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('profiles', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('profiles', 'gender',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', 'BOY', 'GIRL', name='genders'),
               nullable=False)
    # ### end Alembic commands ###
