"""Update profile table

Revision ID: af8029a21f12
Revises: f6079b7ca042
Create Date: 2024-08-29 21:33:54.311135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af8029a21f12'
down_revision: Union[str, None] = 'f6079b7ca042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('profileImages', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('profiles', 'profileImage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('profileImage', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.drop_column('profiles', 'profileImages')
    # ### end Alembic commands ###
