"""Update timestamp to user Table

Revision ID: b8e479ececc6
Revises: 1f77bcec4df9
Create Date: 2024-09-06 21:54:46.525376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8e479ececc6'
down_revision: Union[str, None] = '1f77bcec4df9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('followers', sa.ARRAY(sa.Integer()), nullable=True))
    op.drop_column('profiles', 'followers_id')
    op.add_column('users', sa.Column('registered_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'registered_at')
    op.add_column('profiles', sa.Column('followers_id', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_column('profiles', 'followers')
    # ### end Alembic commands ###
